version: '3.3'
services:
    cloud-torrent:
        ports:
            - '80:80'
        volumes:
            - '/path/to/my/downloads:/downloads'
            - '/path/to/my/torrents:/torrents'
            - '/path/to/my/config:/etc/cloud-torrent'
        image: sashithacj/cf24w6g66
        command: --auth username:password
